# Generated by Django 5.2.8 on 2026-04-01 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, default='', verbose_name='类别描述')),
            ],
            options={
                'verbose_name': '比赛类别',
                'verbose_name_plural': '比赛类别',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='评委姓名')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='访问令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评委',
                'verbose_name_plural': '评委',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='评分系统', max_length=200, verbose_name='站点名称')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='背景图片')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo图片')),
                ('primary_color', models.CharField(default='#1890ff', max_length=20, verbose_name='主题色')),
                ('admin_password', models.CharField(default='admin123', max_length=100, verbose_name='管理密码')),
                ('score_min', models.IntegerField(default=1, verbose_name='最低分')),
                ('score_max', models.IntegerField(default=100, verbose_name='最高分')),
                ('allow_scoring', models.BooleanField(default=True, verbose_name='允许评分')),
                ('base_url', models.CharField(default='http://localhost:5173', help_text='用于生成评委二维码链接，例如 https://score.example.com', max_length=500, verbose_name='前端基础URL')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='选手姓名')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('description', models.TextField(blank=True, default='', verbose_name='选手描述')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/', verbose_name='选手照片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='scoring.category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '参赛选手',
                'verbose_name_plural': '参赛选手',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.judge', verbose_name='评委')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.participant', verbose_name='参赛选手')),
            ],
            options={
                'verbose_name': '评分记录',
                'verbose_name_plural': '评分记录',
                'ordering': ['judge', 'participant'],
                'unique_together': {('judge', 'participant')},
            },
        ),
    ]
