# Generated by Django 5.2.8 on 2026-04-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_score_rules_and_decimal_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='score_value_type',
            field=models.CharField(choices=[('integer', '整数'), ('decimal', '小数'), ('integer_decimal', '整数和小数')], default='integer', max_length=20, verbose_name='合法打分类型'),
        ),
    ]
