# Generated by Django 5.2.8 on 2026-04-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_judge_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['order', 'id'], 'verbose_name': '评委', 'verbose_name_plural': '评委'},
        ),
    ]
