# Generated by Django 5.2.8 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_alter_judge_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='scoring_mode',
            field=models.CharField(
                choices=[('score', '分数模式'), ('vote', '投票模式')],
                default='score',
                max_length=20,
                verbose_name='全局打分模式',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vote_total_count',
            field=models.IntegerField(
                default=10,
                verbose_name='默认投票总数',
                help_text='从多少人中选择',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vote_select_count',
            field=models.IntegerField(
                default=3,
                verbose_name='默认选择人数',
                help_text='选择多少人',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='scoring_mode',
            field=models.CharField(
                choices=[('default', '使用全局设置'), ('score', '分数模式'), ('vote', '投票模式')],
                default='default',
                max_length=20,
                verbose_name='打分模式',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='vote_total_count',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='投票总数',
                help_text='从多少人中选择',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='vote_select_count',
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name='选择人数',
                help_text='选择多少人',
            ),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_order', models.IntegerField(default=0, verbose_name='投票排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('category', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='votes', to='scoring.category', verbose_name='所属类别')),
                ('judge', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='votes', to='scoring.judge', verbose_name='评委')),
                ('participant', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='votes', to='scoring.participant', verbose_name='被选中的参赛选手')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'ordering': ['judge', 'category', 'vote_order'],
                'unique_together': {('judge', 'category', 'participant')},
            },
        ),
    ]
