# Generated by Django 5.2.8 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_scoring_mode_and_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='score_min',
            field=models.DecimalField(
                max_digits=8,
                decimal_places=2,
                blank=True,
                null=True,
                verbose_name='最低分',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='score_max',
            field=models.DecimalField(
                max_digits=8,
                decimal_places=2,
                blank=True,
                null=True,
                verbose_name='最高分',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='score_value_type',
            field=models.CharField(
                max_length=20,
                choices=[('integer', '整数'), ('decimal', '小数'), ('integer_decimal', '整数和小数')],
                blank=True,
                null=True,
                verbose_name='合法打分类型',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='allow_duplicate_scores',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='允许重复打分',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='exclude_extreme_scores',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='统计时去掉最高分和最低分',
            ),
        ),
    ]
