# Generated by OpenCode on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_add_category_score_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exclude_highest_count',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='去掉最高分数量',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='exclude_lowest_count',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='去掉最低分数量',
            ),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exclude_highest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='去掉最高分数量'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='exclude_lowest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='去掉最低分数量'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='exclude_extreme_scores',
            field=models.BooleanField(
                default=False,
                help_text='开启后，统计总分与平均分时按配置数量去掉最低分和最高分。',
                verbose_name='统计时去掉最高分和最低分',
            ),
        ),
    ]
