# Generated by Django 5.2.9 on 2026-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_extreme_score_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, help_text='为空表示该评委可参与全部类别。', related_name='allowed_judges', to='scoring.category', verbose_name='可评分/投票类别'),
        ),
    ]
